name: Deploy using SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH-Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > .env

      # Remove fnm completely from the environment
      - name: Remove fnm and clear related symlinks
        run: |
          # Ensure fnm is uninstalled completely
          rm -rf $HOME/.fnm
          rm -rf /run/user/$(id -u)/fnm_multishells
          rm -f $(which fnm)
          # Unset environment variables
          unset FNM_DIR
          unset FNM_NODE_VERSION
          export PATH=$(echo $PATH | sed -e 's|:$FNM_DIR/bin||')
          echo "fnm completely removed"

      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }} 
          port: 21098
          source: "."
          target: "/home/lsvosolvqm/trenz.dimuthadithya.me/"
          tar_dereference: true
