name: Deploy using SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH-Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
  
