name: Deploy using SSH

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH-Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_CONTENT }}" > .env

      # Disable fnm by cleaning up the environment
      - name: Disable fnm and clean up environment
        run: |
          unset FNM_DIR
          unset FNM_NODE_VERSION
          export PATH=$(echo $PATH | sed -e 's/:$FNM_DIR\/bin//')
          # Remove any existing symlink that could conflict
          rm -rf /run/user/$(id -u)/fnm_multishells

      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }} 
          port: 21098
          source: "."
          target: "/home/lsvosolvqm/trenz.dimuthadithya.me/"
          tar_dereference: true
