name: Deploy to cPanel

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main           # Automatically trigger on push to main

jobs:
  deploy:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22  # Path on the server (change if needed)
          strip_components: 1          # Prevent nesting repo folder
